### ISSUE TITLE
How are Goblet selected on histological images

### ISSUE THREAD

**Issue by CAUiKUN** [Flashiness/METI#2]

**Comment by Flashiness** [comment]
It is based on prior knowledge and pathologist annotation. They are large,
pale, and round. After segmentation, you can get features like area,
length-width ratio, solidity, etc. Those features will help you to filter
them out. Different cell type have different features, so it really
depends on what you want to filter. Hope this helps!

**Comment by CAUiKUN** [comment]
Okay, I see. Thank you very much！

---- Replied Message ----
| From | Jiahui ***@***.***> |
| Date | 09/04/2024 21:16 |
| To | Flashiness/METI ***@***.***> |
| Cc | SJTUiKUN ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Flashiness/METI] How are Goblet selected on histological images (Issue #2) |

It is based on prior knowledge and pathologist annotation. They are large,
pale, and round. After segmentation, you can get features like area,
length-width ratio, solidity, etc. Those features will help you to filter
them out. Different cell type have different features, so it really
depends on what you want to filter. Hope this helps!
