### ISSUE TITLE
How do you tell which is Goblet

### ISSUE THREAD

**Issue by CAUiKUN** [Flashiness/METI#3]
![屏幕截图 2024-09-04 195653](https://github.com/user-attachments/assets/d917c584-b6ea-4aa6-ae2c-5dca14b22d0e)

**Comment by Flashiness** [comment]
This will be based on prior knowledge and also we confirmed with
pathologist. One channel will only contain cell nuclei.

**Comment by CAUiKUN** [comment]
Okay, I see. Thank you very much！

---- Replied Message ----
| From | Jiahui ***@***.***> |
| Date | 09/04/2024 21:20 |
| To | Flashiness/METI ***@***.***> |
| Cc | SJTUiKUN ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Flashiness/METI] How do you tell which is Goblet (Issue #3) |

This will be based on prior knowledge and also we confirmed with
pathologist. One channel will only contain cell nuclei.

**Comment by Flashiness** [comment]
No problem! Let me know if you have any other questions!
