### ISSUE TITLE
Request for Tutorial Data Files

### ISSUE THREAD

**Issue by ReasonBean** [Flashiness/METI#4]
Hello,

First of all, congratulations on the publication of your paper.

I want to follow the METI tutorial, but it seems that the necessary data files are not included in this Github. I am writing about this issue because these files are essential to proceeding with the tutorial, but I couldn't find them in the repository.

Please provide the data files or guide me to where I can download them.

Thank you.

**Comment by Flashiness** [comment]
Thanks for your interest!
You can download our dataset from GEO https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE246011.
If you want to play different data, you can also download public data from 10x genomic website https://www.10xgenomics.com/cn/datasets?query=&page=1&configure%5BhitsPerPage%5D=50&configure%5BmaxValuesPerFacet%5D=1000

**Comment by ReasonBean** [comment]
I appreciate your help. 

I'll give it a try. :)
