### ISSUE TITLE
Does it have to be a full-pixel image?

### ISSUE THREAD

**Issue by xiaomaoxilian** [Flashiness/METI#5]
Thanks for your work, and I have a question.
What to do if there are **only hires images**? How to modify the code that reads the files? 
Is it okay to use that **scal_factor**? and if so, how to use it? 
Thanks again.

**Comment by Flashiness** [comment]
Hi,

Thanks for the interest!
Our method is an integrated tool of HE image and gene expression, so you
can’t do the same analysis if you only have hired images. However, the
segmentation part only requires images, so you can employ that part if you
find it is helpful.

Best,
Jiahui
